bin/sf-install.js
bin/sf-lerna-install.js

Updates `sf-install` script to only  install husky if `.git` folder exists
**QA**:
1: Clone source-tracking: `git@github.com:forcedotcom/source-tracking.git`
2: `yarn link` this PR into source-tracking
3: Run `rm -rf .git` then `yarn install`,  it shouldn't try to install/initialize husky.
@W-10088025@

fix: only install husky if `.git` folder exists

---

.nycrc
bin/sf-test.js
files/nycrc
package.json
utils/husky-init.js
yarn.lock

@W-10290171@
will fix future projects when running `yarn sf-install`

fix: add --forbid-only to husky hook, fix nyc file

---

utils/standardize-pjson.js

Bumps the `engine` prop in `standarize-pjson`, bye node 12 👋🏼 
https://nodejs.org/en/about/releases/
@W-0@

chore: set engine prop to >= node v14

---

utils/standardize-files.js

Fixes `sf-install` so that it won't re-write the LICENSE.txt file on Windows machines with CRLF line endings.
This is really annoying on windows because you have to always make sure you're not accidentally committing those changes on the LICENSE.txt if you run `yarn install` on any repo which uses `sf-install`.

fix: allows files to be correctly compared across operating systems

---

bin/sf-format.js

Makes `sf-format` run on plugin schemas and command snapshots. This will standardize these files so that local environment differences in how they're generated don't affect PR diffs.
[[skip-validate-pr]]

fix: format plugin schemas and snapshots

---

utils/sf-config.js

wireit runs parallel stuff in child process, chalk turns off colors when it thinks it's in a non-tty.  gha > spawn is non-tty.   See https://github.com/chalk/supports-color/issues/106
should fix errors that look like this
- https://github.com/salesforcecli/sf-plugins-core/actions/runs/4289179928/jobs/7471969439#step:8:179
- https://github.com/salesforcecli/plugin-apex/actions/runs/4289713156/jobs/7473025531#step:8:137
proof that it works:
https://github.com/salesforcecli/plugin-apex/actions/runs/4299683299/jobs/7495151921.

fix: force color output on things that use chalk

---

bin/sf-docs.js

preserve perf test results when regenerating docs.
this needs to not delete that dir, but also not cause git conflicts. I don't know enough about worktrees to be sure this is going to work.

feat: don't nuke the entire docs directory

---

utils/write-dependencies.js

fix for https://github.com/forcedotcom/dev-scripts/pull/173 @W-13160311@.
was incorrectly downgrading plugins to match the minimum

fix: use version, not name for minimum versioning

---

utils/write-dependencies.js

bump command-ref to get a version that ignores dev plugins when doing the command-ref topics
https://github.com/salesforcecli/plugin-info/actions/runs/5126588431/jobs/9221273092?pr=420

fix: bump command-ref

---

utils/husky-init.js

Shane found this wasn't working as expected here: https://github.com/forcedotcom/kit/pull/236
Fixes prepush hook not passing `--forbid-only` correctly to `mocha`.
Will use `test:only` instead of `test` script because the latter only specifies an array of dependencies and doesn't work with extra-args. While it's not the same as before (running lint, format, etc on prepush), it helps catching `it.only` statements.
This has been broken since we moved to `wireit` and it's not a breaking change.
@W-13748069@

fix: pass extra arg to wireit script in git hook

---

bin/sf-prepack.js
utils/shelljs.js

Run `oclif lock` during prepack.
Depends on https://github.com/oclif/oclif/pull/1178 and https://github.com/oclif/plugin-plugins/pull/648
@W-14010705@

fix: run oclif lock during prepack

---

utils/sf-config.js
utils/standardize-pjson.js

Allow default wireit scripts to use `bin/dev.js`
@W-14364607@

fix: allow dev.js in wireit scripts

---

README.md
utils/write-dependencies.js

ts-node's register process (ex: `.mocharc.json` looks in top-level node_modules for ts-node.  It's not there, so it fails.
This change leaves ts-node in repos that have it.

fix: keep ts-node

---

utils/sf-config.js

To avoid ESM errors with node v18.19.x when executing dev.js, use node and the ts-node/esm loader.

fix: use node versus ts-node to run scripts

---

utils/write-dependencies.js

lots of open PRs look like https://github.com/salesforcecli/plugin-info/pull/601 but result in https://github.com/salesforcecli/plugin-info/actions/runs/7236645537/job/19715404446?pr=601
This'll bump core and the eslint rules to make those unnecessary

chore: bump eslint plugin min

---

utils/standardize-pjson.js

@W-14053688@
I checked that it turns `:` into ` ` and that it adds the entire line when it doesn't exist (more likely)

feat: plugins have space as oclif.topicSeparator

---

bin/sf-prepack.js
files/gitignore
utils/sf-config.js
utils/standardize-files.js
utils/standardize-pjson.js
utils/write-dependencies.js

- Run `npm shrinkwrap` during `sf-prepack`
- Start managing plugin's `files`
- Add entires to `.gitignore` if they don't exist
- if the `CLEAN` and `CLEAN ALL` segments exist, it will add the entries to the appropriate section (and remove them from anywhere else in the file)
- if those segments don't exist, it will simply append the entries to the bottom of the file
- Change `postpack` script for plugins to `sf-clean`
- Remove `shx` devDep if it's not being used by any script
@W-14878497@

feat: run shrinkwrap during sf-prepack

---

bin/sf-clean.js
package.json
utils/sf-config.js

Adds `--ignore-signing-artifacts` flag to sf-clean to prevent the clean up of `*.sig` and `*.tgz` files that are still needed for plugin signing
Verified by https://github.com/salesforcecli/plugin-settings/actions/runs/8052090396

fix: add --ignore-signing-artifacts flag to sf-clean

---

.github/workflows/update-jit-list.yml
.github/workflows/update-plugin-list.yml
bin/sf-prepack.js
core-plugins.json
jit-plugins.json
utils/project-type.js
utils/standardize-pjson.js

Only generate oclif.lock and npm-shrinkwrap.json for JIT plugins
We'll use a hardcoded list of JIT plugins (`jit-plugins.json`) to check if a given plugin is a JIT plugin. This list will get updated every Wednesday at 14:00 UTC by a cronjob.
@W-15620196@

feat: only generate lockfiles for jit plugins

---

bin/sf-clean.js
package.json
utils/standardize-files.js

Fixes: https://github.com/forcedotcom/dev-scripts/issues/301
Problem:
`sf-install` reads the `.gitignore` in the project and tries to split the content by `\n` (even on windows).
This messes up your gitignore if it uses `CRLF` (most common on windows but can happen on linux/mac too) like in the linked issue above.
dev-scripts now will detect the EOL used by the local file and use that for parsing the content and final write.
We can't use node's `os.EOL` because it assumes unix === `LF` and win === `CRLF`.
same change in `sf-clean`
NOTE:
there's a file check done here to see if the `.gitignore` in the project matches the template:
https://github.com/forcedotcom/dev-scripts/blob/e2efc93a4af12dc5953d1beb673cc768a7e620a6/utils/standardize-files.js#L79 …

fix: respect current EOL in gitignore

---

package.json
yarn.lock

3.0.0 supports 0.26, drops support for older typedoc version

fix(deps): typedoc plugin for v0.26 support

---

package.json
yarn.lock

nyc majors for various dependabot stuff (breaking changes were only node-major-version drops)
eslint-config to push out latest rules everywhere

fix(deps): bump-nyc-and-eslint-config

---

package.json
yarn.lock

Wireit needs to be bumped in our repos for them to be able to work with the new wireit Github Action (new cache).
NOTE: Merge this after the GHA changes https://github.com/salesforcecli/github-workflows/pull/140
See https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CN26RYAT/view for more details.
[@W-18302796@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18302796)

W-18302796: Bump wireit for new cache
