forcedotcom/dev-scripts

bin/sf-test.js

@W-10054968@ align sf-lint and sf-test globs

fix: 10054968

---

utils/standardize-pjson.js
utils/write-dependencies.js

remove `lint-staged` (unused by scripts) and `cz-conventional-changelog` unused by us
@W-10957016@

chore: remove unused linters

---

package.json
yarn.lock

Replace `@oclif/dev-cli` with `oclif`

fix: remove dev-cli

---

bin/sf-docs.js

redo of https://github.com/forcedotcom/dev-scripts/pull/155

feat: don't try to delete top-level

---

utils/write-dependencies.js

rollout for [W-13586057](https://gus.lightning.force.com/a07EE00001Tl80JYAR)

feat: core 5

---

utils/write-dependencies.js

[@W-13887925@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13887925)
https://github.com/oclif/oclif/pull/1186

Ensure oclif 3.16.0 for readme changes

---

.github/workflows/create-github-release.yml

release failure: https://github.com/forcedotcom/dev-scripts/actions/runs/6460805898

fix: don't try to publish a readme for this repo

---

package.json
utils/sf-config.js

So that it can run on windows too

fix: use ts-node to execute bin/dev.js

---

utils/sf-config.js
utils/standardize-pjson.js

fix: improve bin/dev.js check

---

utils/sf-config.js

fix: fix null path

---

package.json
yarn.lock

fix(deps): bump node types to 18

---

package.json
yarn.lock

ex: https://github.com/salesforcecli/plugin-dev/actions/runs/7156226928/job/19485671054?pr=434

fix(deps): bump ts-node

---

utils/sf-config.js

auth and org need examples of mydomain for flags like --instance-url.

feat: allow mydomain examples in docs

---

utils/write-dependencies.js

BREAKING CHANGE: all the libraries with core7 and jsforce-node

feat!: core7 bumps

---

.github/CODEOWNERS

chore: add codeowners file for eccn

---

package.json

fix: publish plugin lists

---

package.json
utils/write-dependencies.js

Depends on https://github.com/salesforcecli/sf-plugins-core/pull/537
@W-15932535@

feat: enforce core v4

---

.prettierignore

fix: no prettier on messages

---

utils/write-dependencies.js

roll out sf-plugins-core v11 to consumers
@W-16036430@

feat: bump to new major version of sf-plugins-core

---

package.json
yarn.lock

fix: dev-config bump for typedoc options update

---

utils/sf-config.js

Ignore localhost links (part of W-17736371)
